'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=s=>/^https:\/\//i.test(s||'')?s:'';
const scopeNames={direct:'Quadruped + arm',adjacent:'Adjacent embodiment',survey:'Survey',background:'Background methods'};
const depths={targeted_fulltext:'Targeted full-text check',abstract:'Abstract checked',metadata:'Metadata checked'};
let data, papers=[],byId=new Map(),favorites=new Set(),filtered=[],page=1,readerLoaded=false,previousRoute='#library',suppressClose=false,currentView=null;
const state={q:'',topic:'',scope:'',robot:'',arm:'',saved:false,sort:'year'};
try{const saved=JSON.parse(localStorage.getItem('la-favorites')||'[]');if(Array.isArray(saved))favorites=new Set(saved.filter(x=>typeof x==='string'));}catch{}
const normalize=s=>String(s).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),2300);}
function persist(){try{localStorage.setItem('la-favorites',JSON.stringify([...favorites]));}catch{toast('Storage is unavailable; saved papers will last for this session only.');}}
function updateSaved(){$('#saved-count').textContent=favorites.size;$$('[data-save]').forEach(b=>{const on=favorites.has(b.dataset.save);b.setAttribute('aria-pressed',String(on));b.textContent=b.classList.contains('bookmark')?(on?'★':'☆'):(on?'★ Saved':'☆ Save');b.setAttribute('aria-label',(on?'Unsave ':'Save ')+(byId.get(b.dataset.save)?.title||''));});}
function toggleSave(id){if(favorites.has(id))favorites.delete(id);else favorites.add(id);persist();updateSaved();if(state.saved)renderLibrary();}
function syncControls(){$('#search').value=state.q;for(const k of ['topic','scope','robot','arm'])$('#'+k+'-filter').value=state[k];$('#sort').value=state.sort;$('#saved-toggle').setAttribute('aria-pressed',String(state.saved));}
function stateHash(){const q=new URLSearchParams();for(const k of ['q','topic','scope','robot','arm'])if(state[k])q.set(k,state[k]);if(state.saved)q.set('saved','1');if(state.sort!=='year')q.set('sort',state.sort);return '#library'+(q.size?'?'+q:'');}
function filterChanged(){page=1;history.replaceState(null,'',stateHash());renderLibrary();}
function renderHome(){$('#stats').innerHTML=[[papers.length,'deduplicated references'],[papers.filter(p=>p.scope==='direct').length,'direct quadruped-arm studies'],[data.subtopics.length,'research directions'],[new Set(papers.flatMap(p=>p.platforms)).size,'recorded platform models']].map(x=>`<div class="stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('');$('#topics').innerHTML=data.subtopics.map((t,i)=>`<a class="topic-card" href="#library?topic=${t.id}"><span class="topic-number">${String(i+1).padStart(2,'0')} ↗</span><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p><span class="topic-bottom"><span>${papers.filter(p=>p.subtopics.includes(t.id)).length} related papers</span><span>Explore →</span></span></a>`).join('');}
function renderLibrary(){const words=normalize(state.q).trim().split(/\s+/).filter(Boolean);filtered=papers.filter(p=>(!state.topic||(p.topics.includes(state.topic)||p.subtopics.includes(state.topic)))&&(!state.scope||p.scope===state.scope)&&(!state.robot||(state.robot==='unknown'?!p.platforms.length:p.platforms.includes(state.robot)))&&(!state.arm||(state.arm==='unknown'?!p.arms.length:p.arms.includes(state.arm)))&&(!state.saved||favorites.has(p.id))&&words.every(w=>p.search.includes(w)));filtered.sort(state.sort==='citation'?(a,b)=>a.number-b.number:state.sort==='title'?(a,b)=>a.title.localeCompare(b.title):(a,b)=>(Number(b.year)||0)-(Number(a.year)||0)||a.number-b.number);const pages=Math.max(1,Math.ceil(filtered.length/20));page=Math.min(Math.max(page,1),pages);$('#result-count').textContent=`${filtered.length} / ${papers.length} papers${state.saved?' · Saved papers':''}`;$('#paper-list').innerHTML=filtered.length?filtered.slice((page-1)*20,page*20).map(p=>`<article class="paper-card"><div><div class="paper-meta"><span>${esc(p.year||'Year not locked')}</span><span>·</span><span>${esc(p.id)}</span><span class="tag ${p.scope}">${scopeNames[p.scope]}</span></div><button class="paper-title" data-paper="${p.id}">${esc(p.title)}</button><p class="authors">${esc(p.authors.split('; ').slice(0,5).join(' · '))}${p.authors.split('; ').length>5?' · et al.':''}</p><p class="paper-summary">${esc(p.abstract||p.contexts[0]?.text||'Open the paper for its primary source and citation context.')}</p><div class="paper-footer"><span class="hardware-label">${esc(p.platforms.length?p.platforms.join(' / '):'Platform not recorded')}${p.setting==='simulation'?' · Simulation':''}</span>${p.facets.slice(0,5).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><button class="bookmark" data-save="${p.id}" aria-pressed="${favorites.has(p.id)}" aria-label="Save ${esc(p.title)}">${favorites.has(p.id)?'★':'☆'}</button></article>`).join(''):'<div class="empty"><strong>No matching papers</strong><p>Try a shorter query or reset the filters.</p><button class="outline" data-reset>Clear all filters</button></div>';$('#pagination').innerHTML=filtered.length?`<button class="outline" data-page="${page-1}" ${page===1?'disabled':''}>← Previous</button><span>${page} / ${pages}</span><button class="outline" data-page="${page+1}" ${page===pages?'disabled':''}>Next →</button>`:'';$('#export').disabled=!filtered.length;updateSaved();}
function citationText(text){return esc(text.replace(/\[([^\]]+)\]\([^)]+\)/g,'$1')).replace(/\[([A-Z][A-Z0-9]*(?:,\s*[A-Z][A-Z0-9]*)*)\]/g,(all,ids)=>{const ks=ids.split(',').map(x=>x.trim());return ks.every(k=>byId.has(k))?ks.map(k=>`<button class="cite" data-paper="${k}" aria-label="View paper ${k}">[${byId.get(k).number}]</button>`).join(' '):all;}).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');}
function showPaper(id){const p=byId.get(id);if(!p){toast('Paper not found');history.replaceState(null,'','#library');return route();}const caveat='Bibliographic years follow submission, publication, or selected-version conventions; they do not uniformly denote first submission.';$('#dialog-id').textContent=`REFERENCE ${String(p.number).padStart(3,'0')} / ${p.id}`;$('#dialog-content').innerHTML=`<div class="paper-meta"><span>${esc(p.year)}</span><span class="tag ${p.scope}">${scopeNames[p.scope]}</span></div><h2 id="dialog-title">${esc(p.title)}</h2><p class="authors">${esc(p.authors)}</p><p class="muted">${p.arxiv?`arXiv ${esc(p.arxiv)}${p.version?'v'+esc(p.version.replace(/^v/,'')):''}`:''}${p.doi?' · DOI '+esc(p.doi):''}</p><div class="detail-links">${safeUrl(p.url)?`<a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Primary source ↗</a>`:''}${safeUrl(p.pdf)?`<a href="${esc(p.pdf)}" target="_blank" rel="noopener noreferrer">Paper PDF ↗</a>`:''}<button data-save="${p.id}" aria-pressed="${favorites.has(p.id)}">☆ Save</button><button data-copy="${p.id}">Copy BibTeX</button><button data-share="${p.id}">Copy link</button></div><div class="hardware-panel"><div><small>ROBOT PLATFORM</small><strong>${esc(p.platforms.join(' / ')||'Not recorded')}</strong></div><div><small>MANIPULATOR</small><strong>${esc(p.arms.join(' / ')||'Not recorded')}</strong></div><div><small>REPORTED STUDY SETTING</small><strong>${({hardware:'Hardware',simulation:'Simulation',mixed:'Simulation & hardware',not_recorded:'Not recorded'})[p.setting]||'Not recorded'}</strong></div>${p.hardwareEvidence?`<details><summary>Platform evidence & source note</summary><p>${esc(p.hardwareEvidence)}</p><p>For multi-platform studies, the setting applies to the paper as a whole; individual platforms may only be evaluated in simulation.</p></details>`:''}</div><p class="muted">${esc(caveat)}</p><section class="detail-section"><h3>Research abstract <span class="muted">/ AUTHOR ABSTRACT</span></h3><p class="abstract-text" lang="en">${esc(p.abstract||'No abstract text is stored in this catalog record. Open the primary source or read the review passages below.')}</p></section><section class="detail-section"><h3>How this paper is used in the review <span class="muted">/ IN CONTEXT</span></h3>${p.contexts.map(c=>`<div class="context-block"><small>${esc(c.section)}</small><p class="context-text" lang="en">${citationText(c.text)}</p></div>`).join('')||'<p>See the citation in the complete review.</p>'}</section><section class="detail-section"><details><summary>Version record & BibTeX</summary><pre class="bibtex">${esc(p.bib)}</pre></details></section>`;if(!$('#paper-dialog').open)$('#paper-dialog').showModal();$('#paper-dialog').scrollTop=0;updateSaved();}
async function loadReader(section){try{if(!readerLoaded){const r=await fetch('review.json');if(!r.ok)throw Error(r.status);const d=await r.json();$('#review-content').innerHTML=d.html;$('#review-nav').innerHTML=d.nav.map((x,i)=>`<a href="#review?section=${x.id}"><span>${String(i+1).padStart(2,'0')}</span> ${esc(x.title)}</a>`).join('');readerLoaded=true;}if(section)document.getElementById(section)?.scrollIntoView({block:'start'});}catch{$('#review-content').innerHTML='<p class="error">The review could not be loaded. Please refresh or read the PDF.</p>';}}
function route(){if(!data)return;const hash=location.hash.slice(1)||'overview';if(hash.startsWith('paper/')){if(!$$('.view').some(x=>!x.hidden)){setView('library');renderLibrary();}return showPaper(decodeURIComponent(hash.slice(6)));}if($('#paper-dialog').open){suppressClose=true;$('#paper-dialog').close();}const [name,query='']=hash.split('?'),view=['overview','library','review'].includes(name)?name:'overview';setView(view);if(view==='library'){const params=new URLSearchParams(query);for(const k of ['q','topic','scope','robot','arm'])state[k]=params.get(k)||'';state.saved=params.get('saved')==='1';state.sort=params.get('sort')||'year';page=1;syncControls();renderLibrary();}if(view==='review')loadReader(new URLSearchParams(query).get('section'));}
function setView(view){if(currentView!==view){currentView=view;requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'instant'}));}$$('.view').forEach(el=>el.hidden=el.id!==view);$$('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===view);if(el.dataset.view===view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});}
function openPaper(id){if(!location.hash.startsWith('#paper/'))previousRoute=location.hash||'#overview';if(location.hash!=='#paper/'+id)history.pushState(null,'','#paper/'+id);showPaper(id);}
function closePaper(){if($('#paper-dialog').open)$('#paper-dialog').close();}
function reset(){Object.assign(state,{q:'',topic:'',scope:'',robot:'',arm:'',saved:false,sort:'year'});syncControls();filterChanged();}
async function copy(text,message){try{await navigator.clipboard.writeText(text);toast(message);}catch{toast('Copy is unavailable. Expand the version record to copy BibTeX manually.');}}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/x-bibtex;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-paper],[data-save],[data-copy],[data-share],[data-page],[data-reset]');if(!b)return;if(b.dataset.paper)openPaper(b.dataset.paper);if(b.dataset.save)toggleSave(b.dataset.save);if(b.dataset.copy)copy(byId.get(b.dataset.copy).bib,'BibTeX copied');if(b.dataset.share)copy(location.href.split('#')[0]+'#paper/'+b.dataset.share,'Paper link copied');if(b.dataset.page){page=Number(b.dataset.page);renderLibrary();$('#result-count').scrollIntoView({block:'start'});}if(b.hasAttribute('data-reset'))reset();});
$('#close-dialog').addEventListener('click',closePaper);$('#paper-dialog').addEventListener('click',e=>{if(e.target===$('#paper-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closePaper();}});$('#paper-dialog').addEventListener('close',()=>{if(suppressClose){suppressClose=false;return;}if(location.hash.startsWith('#paper/')){history.replaceState(null,'',previousRoute);route();}});
$('#search').addEventListener('input',e=>{state.q=e.target.value;clearTimeout(renderLibrary.timer);renderLibrary.timer=setTimeout(filterChanged,120);});for(const k of ['topic','scope','robot','arm'])$('#'+k+'-filter').addEventListener('change',e=>{state[k]=e.target.value;filterChanged();});$('#sort').addEventListener('change',e=>{state.sort=e.target.value;filterChanged();});$('#reset').addEventListener('click',reset);$('#saved-toggle').addEventListener('click',()=>{state.saved=!state.saved;$('#saved-toggle').setAttribute('aria-pressed',String(state.saved));filterChanged();});$('#export').addEventListener('click',()=>download(filtered.map(x=>x.bib).join('\n\n'),'legged-armed-'+filtered.length+'-references.bib'));document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('#paper-dialog').open){e.preventDefault();location.hash='library';setTimeout(()=>$('#search').focus(),0);}});window.addEventListener('hashchange',route);
fetch('data.json').then(r=>{if(!r.ok)throw Error(r.status);return r.json();}).then(d=>{data=d;papers=d.papers;byId=new Map(papers.map(p=>[p.id,p]));for(const p of papers)p.search=normalize([p.title,p.authors,p.id,p.arxiv,p.doi,p.abstract,...p.facets,...p.platforms,...p.arms].join(' '));favorites=new Set([...favorites].filter(id=>byId.has(id)));$('#topic-filter').insertAdjacentHTML('beforeend',data.topics.map(parent=>`<optgroup label="${esc(parent.title)}"><option value="${parent.id}">All ${esc(parent.title.toLowerCase())}</option>${data.subtopics.filter(t=>t.parent===parent.id).map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('')}</optgroup>`).join(''));for(const [id,field] of [['robot-filter','platforms'],['arm-filter','arms']])$('#'+id).insertAdjacentHTML('beforeend',[...new Set(papers.flatMap(p=>p[field]))].sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join(''));renderHome();updateSaved();route();}).catch(err=>{$('#load-error').hidden=false;console.error('Library load failed',err);});
