/* Curated resource directory. No external embeds or runtime dependencies. */
(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>UIIcons.icon(n);let catalogPromise;
const valid=u=>{try{const x=new URL(u);return x.protocol==='https:'&&!x.username&&!x.password;}catch{return false;}};
const link=(u,t,i)=>valid(u)?`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${icon(i)}${esc(t)}${icon('external')}</a>`:'';
async function show(page,params){
 const root=document.getElementById(page+'-root');root.innerHTML='<p role="status">Loading resources…</p>';
 try{
  if(!catalogPromise)catalogPromise=fetch('toolbox-data.json').then(r=>{if(!r.ok)throw Error('Unavailable');return r.json();}).catch(e=>{catalogPromise=null;throw e;});
  const data=await catalogPromise;if(!Array.isArray(data.items))throw Error('Invalid catalog');
  const items=data.items.filter(x=>x.page===page),baseline=page==='baselines',categories=[...new Set(items.map(x=>x.category))];
  root.innerHTML=`<div class="page-heading"><p class="eyebrow">${baseline?'FROM PAPERS TO EXPERIMENTS':'THE ROBOTICS WORKBENCH'}</p><h1>${baseline?'Baselines <span class="serif">& Benchmarks</span>':'Useful tools<span class="serif"> / Toolbox</span>'}</h1><p>${baseline?'Find a training starting point, then choose an evaluation setting that fits your robot.':'Inspect a model. Build a controller. Train and evaluate a policy.'}</p></div><div class="atlas-intro"><div>${icon(baseline?'code':'network')}<strong>${baseline?'Start with your robot':'Start with your workflow'}</strong><p>${baseline?'Visual Whole-Body and DQ-Bench use B1 + Z1. RoboDuet and UMI on Legs provide Go-series + ARX5 references.':'Robot Viewer opens URDF and other robot descriptions in a browser. The collection below connects model inspection, simulation, learning and planning.'}</p></div><a href="${baseline?'#baselines?q=B1':'https://viewer.robotsfan.com/'}" ${baseline?'':'target="_blank" rel="noopener noreferrer"'} class="primary">${baseline?'Find B1 + Z1 resources':'Open Robot Viewer'} ↗</a></div><div class="atlas-controls"><label>Search resources<input type="search" id="${page}-search" placeholder="${baseline?'B1, Z1, MPC, Isaac Gym…':'URDF, simulation, planning…'}"></label><label>${baseline?'Resource type':'Workflow'}<select id="${page}-category"><option value="">All categories</option>${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select></label><button class="outline" id="${page}-reset">Reset</button></div><p class="atlas-count" role="status" aria-live="polite"></p><div class="atlas-grid"></div><p class="atlas-footnote">Source checked ${esc(data.updated)} · Repository and documentation review; training runs have not been reproduced here. License labels describe the listed project, not every dependency or model asset. ${baseline?'Benchmark results should only be compared under matched tasks, embodiments and evaluation protocols.':''}</p>`;
  const search=root.querySelector('input'),select=root.querySelector('select');search.value=params.get('q')||'';select.value=categories.includes(params.get('category'))?params.get('category'):'';
  function render(){const q=search.value.trim().toLowerCase(),rows=items.filter(x=>(!select.value||x.category===select.value)&&[x.name,x.robot,x.stack,x.summary,x.kind,x.category].join(' ').toLowerCase().includes(q));root.querySelector('.atlas-count').textContent=`${rows.length} of ${items.length} resources`;
   root.querySelector('.atlas-grid').innerHTML=rows.length?rows.map(x=>`<article class="atlas-card" id="resource-${esc(x.id)}"><div class="atlas-card-top"><span class="resource-icon">${icon(x.kind.includes('Benchmark')?'network':x.kind==='Browser tool'?'globe':'code')}</span><span class="tag">${esc(x.kind)}</span></div><h2>${esc(x.name)}</h2><p>${esc(x.summary)}</p><dl><dt>${baseline?'Robot / embodiment':'Works with'}</dt><dd>${esc(x.robot)}</dd><dt>Stack</dt><dd>${esc(x.stack)}</dd><dt>License</dt><dd>${esc(x.license)}</dd></dl><details><summary>Usage & setup notes</summary><p>${esc(x.note)}</p>${x.steps.length?`<ol>${x.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>`:''}<p>${link(x.repo,'Repository documentation','book')}</p></details><div class="atlas-links">${link(x.repo,'Code','github')}${link(x.site,baseline?'Project / docs':'Open website','globe')}${x.paper?`<a data-paper="${esc(x.paper)}" href="#paper/${encodeURIComponent(x.paper)}">${icon('paper')}Paper</a>`:''}</div></article>`).join(''):'<div class="empty"><strong>No matching resources</strong>Try a robot name, a framework, or reset the filters.</div>';
  }
  function change(){const p=new URLSearchParams();if(search.value)p.set('q',search.value);if(select.value)p.set('category',select.value);history.replaceState(null,'','#'+page+(p.size?'?'+p:''));render();}
  search.addEventListener('input',change);select.addEventListener('change',change);root.querySelector('button').addEventListener('click',()=>{search.value='';select.value='';change();});render();
 }catch(e){root.innerHTML='<p role="alert">Resources could not be loaded. <button class="outline">Retry</button></p>';root.querySelector('button').onclick=()=>show(page,params);}
}
window.ResourceAtlas={show};
})();
